//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
    public partial class ClaroFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAuditoriaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private object errorOrigenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idAuditoria {
            get {
                return this.idAuditoriaField;
            }
            set {
                this.idAuditoriaField = value;
                this.RaisePropertyChanged("idAuditoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
                this.RaisePropertyChanged("ubicacionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object errorOrigen {
            get {
                return this.errorOrigenField;
            }
            set {
                this.errorOrigenField = value;
                this.RaisePropertyChanged("errorOrigen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="HeaderResponseType", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    public partial class HeaderResponseType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
                this.RaisePropertyChanged("idTransaccionESB");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
                this.RaisePropertyChanged("nodoAdicional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="HeaderRequestType", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    public partial class HeaderRequestType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string canalField;
        
        private string idAplicacionField;
        
        private string usuarioAplicacionField;
        
        private string usuarioSesionField;
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idAplicacion {
            get {
                return this.idAplicacionField;
            }
            set {
                this.idAplicacionField = value;
                this.RaisePropertyChanged("idAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioSesion {
            get {
                return this.usuarioSesionField;
            }
            set {
                this.usuarioSesionField = value;
                this.RaisePropertyChanged("usuarioSesion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
                this.RaisePropertyChanged("idTransaccionESB");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
                this.RaisePropertyChanged("nodoAdicional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string codeField;
        
        private string messageField;
        
        private string msgidField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgid {
            get {
                return this.msgidField;
            }
            set {
                this.msgidField = value;
                this.RaisePropertyChanged("msgid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consumerField;
        
        private string pidField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private ArgType[] varArgField;
        
        private StatusType statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class ArgType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string languageField;
        
        private string consumerField;
        
        private string systemField;
        
        private string moduloField;
        
        private string pidField;
        
        private string userIdField;
        
        private string dispositivoField;
        
        private string wsIpField;
        
        private string operationField;
        
        private System.DateTime timestampField;
        
        private string msgTypeField;
        
        private ArgType[] varArgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
                this.RaisePropertyChanged("modulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string wsIp {
            get {
                return this.wsIpField;
            }
            set {
                this.wsIpField = value;
                this.RaisePropertyChanged("wsIp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataObtenerTabConsultaPlanTFIPost/v" +
        "1/")]
    public partial class TabConsultaPlanTFIPostType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string providerField;
        
        private string tariffField;
        
        private string suscriberField;
        
        private string desc_planField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("provider");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
                this.RaisePropertyChanged("tariff");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string suscriber {
            get {
                return this.suscriberField;
            }
            set {
                this.suscriberField = value;
                this.RaisePropertyChanged("suscriber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string desc_plan {
            get {
                return this.desc_planField;
            }
            set {
                this.desc_planField = value;
                this.RaisePropertyChanged("desc_plan");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataObtenerTabConsultaPlanTFIPost/v" +
        "1/")]
    public partial class ResponseDataObtenerTabConsultaPlanTFIPostType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TabConsultaPlanTFIPostType[] listaTabConsultaPlanTFIPostField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tabConsultaPlanTFIPost", IsNullable=false)]
        public TabConsultaPlanTFIPostType[] listaTabConsultaPlanTFIPost {
            get {
                return this.listaTabConsultaPlanTFIPostField;
            }
            set {
                this.listaTabConsultaPlanTFIPostField = value;
                this.RaisePropertyChanged("listaTabConsultaPlanTFIPost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/consultaPlanTFI/obtenerTabConsultaPlanTFIPost/v1/" +
        "")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private string origenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                this.descripcionRespuestaField = value;
                this.RaisePropertyChanged("descripcionRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
                this.RaisePropertyChanged("ubicacionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("origen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/consultaPlanTFI/obtenerTabConsultaPlanTFIPost/v1/" +
        "")]
    public partial class obtenerTabConsultaPlanTFIPostResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseStatus responseStatusField;
        
        private ResponseDataObtenerTabConsultaPlanTFIPostType responseDataObtenerTabConsultaPlanTFIPostField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseDataObtenerTabConsultaPlanTFIPostType responseDataObtenerTabConsultaPlanTFIPost {
            get {
                return this.responseDataObtenerTabConsultaPlanTFIPostField;
            }
            set {
                this.responseDataObtenerTabConsultaPlanTFIPostField = value;
                this.RaisePropertyChanged("responseDataObtenerTabConsultaPlanTFIPost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/consultaPlanTFI/obtenerTabConsultaPlanTFIPost/v1/" +
        "")]
    public partial class obtenerTabConsultaPlanTFIPostRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string suscriptorField;
        
        private string proveedorField;
        
        private string tarifaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string suscriptor {
            get {
                return this.suscriptorField;
            }
            set {
                this.suscriptorField = value;
                this.RaisePropertyChanged("suscriptor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
                this.RaisePropertyChanged("proveedor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/esb/postventa/consultaPlanTFI/v1/", ConfigurationName="SIAC.PlanesTFI.relacionConsultaPlanTFIPort")]
    public interface relacionConsultaPlanTFIPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación obtenerTabConsultaPlanTFIPost no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/esb/postventa/relacionConsultaPlanTFI/v1/obtenerTabConsultaPl" +
            "anTFIPost", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.ClaroFault), Action="http://claro.com.pe/esb/postventa/relacionConsultaPlanTFI/v1/obtenerTabConsultaPl" +
            "anTFIPost", Name="claroFault", Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderResponseType1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderRequestType1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderRequestType))]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponse obtenerTabConsultaPlanTFIPost(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTabConsultaPlanTFIPostRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType HeaderRequest;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="headerRequest", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType1 headerRequest1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTabConsultaPlanTFIPostRequest", Namespace="http://claro.com.pe/esb/message/consultaPlanTFI/obtenerTabConsultaPlanTFIPost/v1/" +
            "", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequestType obtenerTabConsultaPlanTFIPostRequest1;
        
        public obtenerTabConsultaPlanTFIPostRequest() {
        }
        
        public obtenerTabConsultaPlanTFIPostRequest(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType1 headerRequest1, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequestType obtenerTabConsultaPlanTFIPostRequest1) {
            this.HeaderRequest = HeaderRequest;
            this.headerRequest1 = headerRequest1;
            this.obtenerTabConsultaPlanTFIPostRequest1 = obtenerTabConsultaPlanTFIPostRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerTabConsultaPlanTFIPostResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType HeaderResponse;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="headerResponse", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType1 headerResponse1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerTabConsultaPlanTFIPostResponse", Namespace="http://claro.com.pe/esb/message/consultaPlanTFI/obtenerTabConsultaPlanTFIPost/v1/" +
            "", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponseType obtenerTabConsultaPlanTFIPostResponse1;
        
        public obtenerTabConsultaPlanTFIPostResponse() {
        }
        
        public obtenerTabConsultaPlanTFIPostResponse(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType HeaderResponse, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType1 headerResponse1, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponseType obtenerTabConsultaPlanTFIPostResponse1) {
            this.HeaderResponse = HeaderResponse;
            this.headerResponse1 = headerResponse1;
            this.obtenerTabConsultaPlanTFIPostResponse1 = obtenerTabConsultaPlanTFIPostResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface relacionConsultaPlanTFIPortChannel : Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.relacionConsultaPlanTFIPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class relacionConsultaPlanTFIPortClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.relacionConsultaPlanTFIPort>, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.relacionConsultaPlanTFIPort {
        
        public relacionConsultaPlanTFIPortClient() {
        }
        
        public relacionConsultaPlanTFIPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public relacionConsultaPlanTFIPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public relacionConsultaPlanTFIPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public relacionConsultaPlanTFIPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponse Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.relacionConsultaPlanTFIPort.obtenerTabConsultaPlanTFIPost(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequest request) {
            return base.Channel.obtenerTabConsultaPlanTFIPost(request);
        }
        
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType obtenerTabConsultaPlanTFIPost(Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderRequestType1 headerRequest1, Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequestType obtenerTabConsultaPlanTFIPostRequest1, out Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.HeaderResponseType1 headerResponse1, out Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponseType obtenerTabConsultaPlanTFIPostResponse1) {
            Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequest inValue = new Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.headerRequest1 = headerRequest1;
            inValue.obtenerTabConsultaPlanTFIPostRequest1 = obtenerTabConsultaPlanTFIPostRequest1;
            Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.obtenerTabConsultaPlanTFIPostResponse retVal = ((Claro.SIACU.ProxyService.Transac.Service.SIAC.PlanesTFI.relacionConsultaPlanTFIPort)(this)).obtenerTabConsultaPlanTFIPost(inValue);
            headerResponse1 = retVal.headerResponse1;
            obtenerTabConsultaPlanTFIPostResponse1 = retVal.obtenerTabConsultaPlanTFIPostResponse1;
            return retVal.HeaderResponse;
        }
    }
}
