//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SIACU.ProxyService.Transac.Service.ActivaDesactivaServicioComercialWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsActivaDesactivaServicioComercialSoapBinding", Namespace="http://pe.com.claro.esb.services")]
    public partial class EbsActivaDesactivaServicioComercial : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validarActivaDesactivaServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ejecutaActivaDesactivaServiciosProgramadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback activaDesactivaServiciosProgOperationCompleted;
        
        private System.Threading.SendOrPostCallback activaDesactivaServicioComercialOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EbsActivaDesactivaServicioComercial() {
            this.Url = global::Claro.SIACU.ProxyService.Transac.Service.Properties.Settings.Default.Claro_SIACU_ProxyService_Transac_Service_ActivaDesactivaServicioComercialWS_EbsActivaDesactivaServicioComercial;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validarActivaDesactivaServiciosCompletedEventHandler validarActivaDesactivaServiciosCompleted;
        
        /// <remarks/>
        public event ejecutaActivaDesactivaServiciosProgramadoCompletedEventHandler ejecutaActivaDesactivaServiciosProgramadoCompleted;
        
        /// <remarks/>
        public event activaDesactivaServiciosProgCompletedEventHandler activaDesactivaServiciosProgCompleted;
        
        /// <remarks/>
        public event activaDesactivaServicioComercialCompletedEventHandler activaDesactivaServicioComercialCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe.com.claro.esb.services", ResponseNamespace="http://pe.com.claro.esb.services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidarActivaDesactivaServiciosResponse", Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
        public ValidarActivaDesactivaServiciosResponse validarActivaDesactivaServicios([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")] ValidarActivaDesactivaServiciosRequest ValidarActivaDesactivaServiciosRequest) {
            object[] results = this.Invoke("validarActivaDesactivaServicios", new object[] {
                        ValidarActivaDesactivaServiciosRequest});
            return ((ValidarActivaDesactivaServiciosResponse)(results[0]));
        }
        
        /// <remarks/>
        public void validarActivaDesactivaServiciosAsync(ValidarActivaDesactivaServiciosRequest ValidarActivaDesactivaServiciosRequest) {
            this.validarActivaDesactivaServiciosAsync(ValidarActivaDesactivaServiciosRequest, null);
        }
        
        /// <remarks/>
        public void validarActivaDesactivaServiciosAsync(ValidarActivaDesactivaServiciosRequest ValidarActivaDesactivaServiciosRequest, object userState) {
            if ((this.validarActivaDesactivaServiciosOperationCompleted == null)) {
                this.validarActivaDesactivaServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarActivaDesactivaServiciosOperationCompleted);
            }
            this.InvokeAsync("validarActivaDesactivaServicios", new object[] {
                        ValidarActivaDesactivaServiciosRequest}, this.validarActivaDesactivaServiciosOperationCompleted, userState);
        }
        
        private void OnvalidarActivaDesactivaServiciosOperationCompleted(object arg) {
            if ((this.validarActivaDesactivaServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarActivaDesactivaServiciosCompleted(this, new validarActivaDesactivaServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe.com.claro.esb.services", ResponseNamespace="http://pe.com.claro.esb.services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EjecutaActivaDesactivaServiciosProgramadoResponse", Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
        public EjecutaActivaDesactivaServiciosProgramadoResponse ejecutaActivaDesactivaServiciosProgramado([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")] EjecutaActivaDesactivaServiciosProgramadoRequest EjecutaActivaDesactivaServiciosProgramadoRequest) {
            object[] results = this.Invoke("ejecutaActivaDesactivaServiciosProgramado", new object[] {
                        EjecutaActivaDesactivaServiciosProgramadoRequest});
            return ((EjecutaActivaDesactivaServiciosProgramadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ejecutaActivaDesactivaServiciosProgramadoAsync(EjecutaActivaDesactivaServiciosProgramadoRequest EjecutaActivaDesactivaServiciosProgramadoRequest) {
            this.ejecutaActivaDesactivaServiciosProgramadoAsync(EjecutaActivaDesactivaServiciosProgramadoRequest, null);
        }
        
        /// <remarks/>
        public void ejecutaActivaDesactivaServiciosProgramadoAsync(EjecutaActivaDesactivaServiciosProgramadoRequest EjecutaActivaDesactivaServiciosProgramadoRequest, object userState) {
            if ((this.ejecutaActivaDesactivaServiciosProgramadoOperationCompleted == null)) {
                this.ejecutaActivaDesactivaServiciosProgramadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnejecutaActivaDesactivaServiciosProgramadoOperationCompleted);
            }
            this.InvokeAsync("ejecutaActivaDesactivaServiciosProgramado", new object[] {
                        EjecutaActivaDesactivaServiciosProgramadoRequest}, this.ejecutaActivaDesactivaServiciosProgramadoOperationCompleted, userState);
        }
        
        private void OnejecutaActivaDesactivaServiciosProgramadoOperationCompleted(object arg) {
            if ((this.ejecutaActivaDesactivaServiciosProgramadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ejecutaActivaDesactivaServiciosProgramadoCompleted(this, new ejecutaActivaDesactivaServiciosProgramadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe.com.claro.esb.services", ResponseNamespace="http://pe.com.claro.esb.services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ActivaDesactivaServiciosProgResponse", Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
        public ActivaDesactivaServiciosProgResponse activaDesactivaServiciosProg([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")] ActivaDesactivaServiciosProgRequest ActivaDesactivaServiciosProgRequest) {
            object[] results = this.Invoke("activaDesactivaServiciosProg", new object[] {
                        ActivaDesactivaServiciosProgRequest});
            return ((ActivaDesactivaServiciosProgResponse)(results[0]));
        }
        
        /// <remarks/>
        public void activaDesactivaServiciosProgAsync(ActivaDesactivaServiciosProgRequest ActivaDesactivaServiciosProgRequest) {
            this.activaDesactivaServiciosProgAsync(ActivaDesactivaServiciosProgRequest, null);
        }
        
        /// <remarks/>
        public void activaDesactivaServiciosProgAsync(ActivaDesactivaServiciosProgRequest ActivaDesactivaServiciosProgRequest, object userState) {
            if ((this.activaDesactivaServiciosProgOperationCompleted == null)) {
                this.activaDesactivaServiciosProgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactivaDesactivaServiciosProgOperationCompleted);
            }
            this.InvokeAsync("activaDesactivaServiciosProg", new object[] {
                        ActivaDesactivaServiciosProgRequest}, this.activaDesactivaServiciosProgOperationCompleted, userState);
        }
        
        private void OnactivaDesactivaServiciosProgOperationCompleted(object arg) {
            if ((this.activaDesactivaServiciosProgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.activaDesactivaServiciosProgCompleted(this, new activaDesactivaServiciosProgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe.com.claro.esb.services", ResponseNamespace="http://pe.com.claro.esb.services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ActivDesactivServicioComercialResponse", Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
        public ActivDesactivServicioComercialResponse activaDesactivaServicioComercial([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")] ActivDesactivServicioComercialRequest ActivDesactivServicioComercialRequest) {
            object[] results = this.Invoke("activaDesactivaServicioComercial", new object[] {
                        ActivDesactivServicioComercialRequest});
            return ((ActivDesactivServicioComercialResponse)(results[0]));
        }
        
        /// <remarks/>
        public void activaDesactivaServicioComercialAsync(ActivDesactivServicioComercialRequest ActivDesactivServicioComercialRequest) {
            this.activaDesactivaServicioComercialAsync(ActivDesactivServicioComercialRequest, null);
        }
        
        /// <remarks/>
        public void activaDesactivaServicioComercialAsync(ActivDesactivServicioComercialRequest ActivDesactivServicioComercialRequest, object userState) {
            if ((this.activaDesactivaServicioComercialOperationCompleted == null)) {
                this.activaDesactivaServicioComercialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactivaDesactivaServicioComercialOperationCompleted);
            }
            this.InvokeAsync("activaDesactivaServicioComercial", new object[] {
                        ActivDesactivServicioComercialRequest}, this.activaDesactivaServicioComercialOperationCompleted, userState);
        }
        
        private void OnactivaDesactivaServicioComercialOperationCompleted(object arg) {
            if ((this.activaDesactivaServicioComercialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.activaDesactivaServicioComercialCompleted(this, new activaDesactivaServicioComercialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ValidarActivaDesactivaServiciosRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string msisdnField;
        
        private string co_idField;
        
        private string co_serField;
        
        private string tip_regField;
        
        private string cod_servField;
        
        private string servc_estadoField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string co_id {
            get {
                return this.co_idField;
            }
            set {
                this.co_idField = value;
            }
        }
        
        /// <remarks/>
        public string co_ser {
            get {
                return this.co_serField;
            }
            set {
                this.co_serField = value;
            }
        }
        
        /// <remarks/>
        public string tip_reg {
            get {
                return this.tip_regField;
            }
            set {
                this.tip_regField = value;
            }
        }
        
        /// <remarks/>
        public string cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
        
        /// <remarks/>
        public string servc_estado {
            get {
                return this.servc_estadoField;
            }
            set {
                this.servc_estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ValidarActivaDesactivaServiciosResponse {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        private string co_serField;
        
        private string tip_regField;
        
        private string cod_servField;
        
        private System.DateTime programacionField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string co_ser {
            get {
                return this.co_serField;
            }
            set {
                this.co_serField = value;
            }
        }
        
        /// <remarks/>
        public string tip_reg {
            get {
                return this.tip_regField;
            }
            set {
                this.tip_regField = value;
            }
        }
        
        /// <remarks/>
        public string cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime programacion {
            get {
                return this.programacionField;
            }
            set {
                this.programacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class EjecutaActivaDesactivaServiciosProgramadoRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private System.DateTime fecha_ejecucionField;
        
        private string codigo_servicioField;
        
        private string usuario_sistemaField;
        
        private string usuario_aplicacionField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha_ejecucion {
            get {
                return this.fecha_ejecucionField;
            }
            set {
                this.fecha_ejecucionField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_servicio {
            get {
                return this.codigo_servicioField;
            }
            set {
                this.codigo_servicioField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_sistema {
            get {
                return this.usuario_sistemaField;
            }
            set {
                this.usuario_sistemaField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_aplicacion {
            get {
                return this.usuario_aplicacionField;
            }
            set {
                this.usuario_aplicacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class EjecutaActivaDesactivaServiciosProgramadoResponse {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ActivaDesactivaServiciosProgRequest {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string msisdnField;
        
        private string co_idField;
        
        private string customer_idField;
        
        private string co_serField;
        
        private string flag_occ_apadeceField;
        
        private double monto_fid_apadeceField;
        
        private double nuevo_CFField;
        
        private string tipo_regField;
        
        private int ciclo_factField;
        
        private string cod_servField;
        
        private string desc_servField;
        
        private string nro_cuentaField;
        
        private string usuario_aplicacionField;
        
        private string usuario_sistemaField;
        
        private System.DateTime fecha_progField;
        
        private System.DateTime fecha_regField;
        
        private string id_interaccionField;
        
        private string tipo_servicioField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string co_id {
            get {
                return this.co_idField;
            }
            set {
                this.co_idField = value;
            }
        }
        
        /// <remarks/>
        public string customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public string co_ser {
            get {
                return this.co_serField;
            }
            set {
                this.co_serField = value;
            }
        }
        
        /// <remarks/>
        public string flag_occ_apadece {
            get {
                return this.flag_occ_apadeceField;
            }
            set {
                this.flag_occ_apadeceField = value;
            }
        }
        
        /// <remarks/>
        public double monto_fid_apadece {
            get {
                return this.monto_fid_apadeceField;
            }
            set {
                this.monto_fid_apadeceField = value;
            }
        }
        
        /// <remarks/>
        public double nuevo_CF {
            get {
                return this.nuevo_CFField;
            }
            set {
                this.nuevo_CFField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_reg {
            get {
                return this.tipo_regField;
            }
            set {
                this.tipo_regField = value;
            }
        }
        
        /// <remarks/>
        public int ciclo_fact {
            get {
                return this.ciclo_factField;
            }
            set {
                this.ciclo_factField = value;
            }
        }
        
        /// <remarks/>
        public string cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
        
        /// <remarks/>
        public string desc_serv {
            get {
                return this.desc_servField;
            }
            set {
                this.desc_servField = value;
            }
        }
        
        /// <remarks/>
        public string nro_cuenta {
            get {
                return this.nro_cuentaField;
            }
            set {
                this.nro_cuentaField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_aplicacion {
            get {
                return this.usuario_aplicacionField;
            }
            set {
                this.usuario_aplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_sistema {
            get {
                return this.usuario_sistemaField;
            }
            set {
                this.usuario_sistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha_prog {
            get {
                return this.fecha_progField;
            }
            set {
                this.fecha_progField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha_reg {
            get {
                return this.fecha_regField;
            }
            set {
                this.fecha_regField = value;
            }
        }
        
        /// <remarks/>
        public string id_interaccion {
            get {
                return this.id_interaccionField;
            }
            set {
                this.id_interaccionField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_servicio {
            get {
                return this.tipo_servicioField;
            }
            set {
                this.tipo_servicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ActivaDesactivaServiciosProgResponse {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        private string co_serField;
        
        private string tip_regField;
        
        private string cod_servField;
        
        private System.DateTime programacionField;
        
        /// <remarks/>
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
            }
        }
        
        /// <remarks/>
        public string co_ser {
            get {
                return this.co_serField;
            }
            set {
                this.co_serField = value;
            }
        }
        
        /// <remarks/>
        public string tip_reg {
            get {
                return this.tip_regField;
            }
            set {
                this.tip_regField = value;
            }
        }
        
        /// <remarks/>
        public string cod_serv {
            get {
                return this.cod_servField;
            }
            set {
                this.cod_servField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime programacion {
            get {
                return this.programacionField;
            }
            set {
                this.programacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ActivDesactivServicioComercialRequest {
        
        private string co_idField;
        
        private string p_co_serField;
        
        private string p_tipregField;
        
        private string usuarioField;
        
        private string aplicacionField;
        
        private string estacionField;
        
        private string servidorField;
        
        private string fecha_horaField;
        
        private string id_transaccionField;
        
        /// <remarks/>
        public string co_id {
            get {
                return this.co_idField;
            }
            set {
                this.co_idField = value;
            }
        }
        
        /// <remarks/>
        public string p_co_ser {
            get {
                return this.p_co_serField;
            }
            set {
                this.p_co_serField = value;
            }
        }
        
        /// <remarks/>
        public string p_tipreg {
            get {
                return this.p_tipregField;
            }
            set {
                this.p_tipregField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string estacion {
            get {
                return this.estacionField;
            }
            set {
                this.estacionField = value;
            }
        }
        
        /// <remarks/>
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
            }
        }
        
        /// <remarks/>
        public string fecha_hora {
            get {
                return this.fecha_horaField;
            }
            set {
                this.fecha_horaField = value;
            }
        }
        
        /// <remarks/>
        public string id_transaccion {
            get {
                return this.id_transaccionField;
            }
            set {
                this.id_transaccionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/serviciocomercial/schemas/ServicioComercial")]
    public partial class ActivDesactivServicioComercialResponse {
        
        private string v_errnumField;
        
        private string v_errmsjField;
        
        /// <remarks/>
        public string v_errnum {
            get {
                return this.v_errnumField;
            }
            set {
                this.v_errnumField = value;
            }
        }
        
        /// <remarks/>
        public string v_errmsj {
            get {
                return this.v_errmsjField;
            }
            set {
                this.v_errmsjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void validarActivaDesactivaServiciosCompletedEventHandler(object sender, validarActivaDesactivaServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarActivaDesactivaServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarActivaDesactivaServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidarActivaDesactivaServiciosResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidarActivaDesactivaServiciosResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void ejecutaActivaDesactivaServiciosProgramadoCompletedEventHandler(object sender, ejecutaActivaDesactivaServiciosProgramadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ejecutaActivaDesactivaServiciosProgramadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ejecutaActivaDesactivaServiciosProgramadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EjecutaActivaDesactivaServiciosProgramadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EjecutaActivaDesactivaServiciosProgramadoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void activaDesactivaServiciosProgCompletedEventHandler(object sender, activaDesactivaServiciosProgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class activaDesactivaServiciosProgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal activaDesactivaServiciosProgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActivaDesactivaServiciosProgResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActivaDesactivaServiciosProgResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    public delegate void activaDesactivaServicioComercialCompletedEventHandler(object sender, activaDesactivaServicioComercialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1532.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class activaDesactivaServicioComercialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal activaDesactivaServicioComercialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ActivDesactivServicioComercialResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ActivDesactivServicioComercialResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591