//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Claro.SIACU.ProxyService.Transac.Service.InstantLinkSOA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'PolicyReference' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InstantLinkWebServicesPortBinding", Namespace="http://soa.comptel.com/2011/02/instantlink")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InstantLinkRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Notification[]))]
    public partial class InstantLinkWebServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback displayOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInstantLinkAvailabilityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InstantLinkWebServices() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://172.19.32.88:44006/ilws/InstantLinkSOA";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event modifyCompletedEventHandler modifyCompleted;
        
        /// <remarks/>
        public event displayCompletedEventHandler displayCompleted;
        
        /// <remarks/>
        public event getInstantLinkAvailabilityCompletedEventHandler getInstantLinkAvailabilityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://soa.comptel.com/2011/02/instantlink")]
        public Response delete([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")] DeleteRequest DeleteRequest) {
            object[] results = this.Invoke("delete", new object[] {
                        DeleteRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(DeleteRequest DeleteRequest) {
            this.deleteAsync(DeleteRequest, null);
        }
        
        /// <remarks/>
        public void deleteAsync(DeleteRequest DeleteRequest, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        DeleteRequest}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://soa.comptel.com/2011/02/instantlink")]
        public Response create([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")] CreateRequest CreateRequest) {
            object[] results = this.Invoke("create", new object[] {
                        CreateRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(CreateRequest CreateRequest) {
            this.createAsync(CreateRequest, null);
        }
        
        /// <remarks/>
        public void createAsync(CreateRequest CreateRequest, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        CreateRequest}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://soa.comptel.com/2011/02/instantlink")]
        public Response modify([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")] ModifyRequest ModifyRequest) {
            object[] results = this.Invoke("modify", new object[] {
                        ModifyRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void modifyAsync(ModifyRequest ModifyRequest) {
            this.modifyAsync(ModifyRequest, null);
        }
        
        /// <remarks/>
        public void modifyAsync(ModifyRequest ModifyRequest, object userState) {
            if ((this.modifyOperationCompleted == null)) {
                this.modifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyOperationCompleted);
            }
            this.InvokeAsync("modify", new object[] {
                        ModifyRequest}, this.modifyOperationCompleted, userState);
        }
        
        private void OnmodifyOperationCompleted(object arg) {
            if ((this.modifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyCompleted(this, new modifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("Response", Namespace="http://soa.comptel.com/2011/02/instantlink")]
        public Response display([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")] DisplayRequest DisplayRequest) {
            object[] results = this.Invoke("display", new object[] {
                        DisplayRequest});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void displayAsync(DisplayRequest DisplayRequest) {
            this.displayAsync(DisplayRequest, null);
        }
        
        /// <remarks/>
        public void displayAsync(DisplayRequest DisplayRequest, object userState) {
            if ((this.displayOperationCompleted == null)) {
                this.displayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisplayOperationCompleted);
            }
            this.InvokeAsync("display", new object[] {
                        DisplayRequest}, this.displayOperationCompleted, userState);
        }
        
        private void OndisplayOperationCompleted(object arg) {
            if ((this.displayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.displayCompleted(this, new displayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("InstantLinkAvailabilityInfo", Namespace="http://soa.comptel.com/2011/02/instantlink")]
        public InstantLinkAvailabilityInfo getInstantLinkAvailability() {
            object[] results = this.Invoke("getInstantLinkAvailability", new object[0]);
            return ((InstantLinkAvailabilityInfo)(results[0]));
        }
        
        /// <remarks/>
        public void getInstantLinkAvailabilityAsync() {
            this.getInstantLinkAvailabilityAsync(null);
        }
        
        /// <remarks/>
        public void getInstantLinkAvailabilityAsync(object userState) {
            if ((this.getInstantLinkAvailabilityOperationCompleted == null)) {
                this.getInstantLinkAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInstantLinkAvailabilityOperationCompleted);
            }
            this.InvokeAsync("getInstantLinkAvailability", new object[0], this.getInstantLinkAvailabilityOperationCompleted, userState);
        }
        
        private void OngetInstantLinkAvailabilityOperationCompleted(object arg) {
            if ((this.getInstantLinkAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInstantLinkAvailabilityCompleted(this, new getInstantLinkAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class DeleteRequest : InstantLinkRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public abstract partial class InstantLinkRequest {
        
        private RequestHeader requestHeaderField;
        
        private Parameter[] requestParametersField;
        
        /// <remarks/>
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Parameter[] RequestParameters {
            get {
                return this.requestParametersField;
            }
            set {
                this.requestParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class RequestHeader {
        
        private string neTypeField;
        
        private string orderNoField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private string reqUserField;
        
        private System.DateTime reqStartTimeField;
        
        private bool reqStartTimeFieldSpecified;
        
        private MaxReqTime maxReqTimeField;
        
        private bool retransmissionFlagField;
        
        private bool retransmissionFlagFieldSpecified;
        
        private string retransmissionKeyField;
        
        private bool bypassLockField;
        
        private bool bypassLockFieldSpecified;
        
        private bool addNotificationsToResponseField;
        
        private bool addNotificationsToResponseFieldSpecified;
        
        private int notificationMsgLevelField;
        
        private bool notificationMsgLevelFieldSpecified;
        
        /// <remarks/>
        public string NeType {
            get {
                return this.neTypeField;
            }
            set {
                this.neTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReqUser {
            get {
                return this.reqUserField;
            }
            set {
                this.reqUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReqStartTime {
            get {
                return this.reqStartTimeField;
            }
            set {
                this.reqStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReqStartTimeSpecified {
            get {
                return this.reqStartTimeFieldSpecified;
            }
            set {
                this.reqStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MaxReqTime MaxReqTime {
            get {
                return this.maxReqTimeField;
            }
            set {
                this.maxReqTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool RetransmissionFlag {
            get {
                return this.retransmissionFlagField;
            }
            set {
                this.retransmissionFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetransmissionFlagSpecified {
            get {
                return this.retransmissionFlagFieldSpecified;
            }
            set {
                this.retransmissionFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string RetransmissionKey {
            get {
                return this.retransmissionKeyField;
            }
            set {
                this.retransmissionKeyField = value;
            }
        }
        
        /// <remarks/>
        public bool BypassLock {
            get {
                return this.bypassLockField;
            }
            set {
                this.bypassLockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BypassLockSpecified {
            get {
                return this.bypassLockFieldSpecified;
            }
            set {
                this.bypassLockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AddNotificationsToResponse {
            get {
                return this.addNotificationsToResponseField;
            }
            set {
                this.addNotificationsToResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddNotificationsToResponseSpecified {
            get {
                return this.addNotificationsToResponseFieldSpecified;
            }
            set {
                this.addNotificationsToResponseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int NotificationMsgLevel {
            get {
                return this.notificationMsgLevelField;
            }
            set {
                this.notificationMsgLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotificationMsgLevelSpecified {
            get {
                return this.notificationMsgLevelFieldSpecified;
            }
            set {
                this.notificationMsgLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class MaxReqTime {
        
        private MaxReqTimeUnit unitField;
        
        private int valueField;
        
        public MaxReqTime() {
            this.unitField = MaxReqTimeUnit.minutes;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(MaxReqTimeUnit.minutes)]
        public MaxReqTimeUnit unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public enum MaxReqTimeUnit {
        
        /// <remarks/>
        minutes,
        
        /// <remarks/>
        seconds,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class InstantLinkAvailabilityInfo {
        
        private string instantLinkInstanceField;
        
        private AvailInfoStatus runningStatusField;
        
        private long uptimeField;
        
        /// <remarks/>
        public string InstantLinkInstance {
            get {
                return this.instantLinkInstanceField;
            }
            set {
                this.instantLinkInstanceField = value;
            }
        }
        
        /// <remarks/>
        public AvailInfoStatus RunningStatus {
            get {
                return this.runningStatusField;
            }
            set {
                this.runningStatusField = value;
            }
        }
        
        /// <remarks/>
        public long Uptime {
            get {
                return this.uptimeField;
            }
            set {
                this.uptimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public enum AvailInfoStatus {
        
        /// <remarks/>
        Starting,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not reachable")]
        Notreachable,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("No response")]
        Noresponse,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class Notification {
        
        private string orderNoField;
        
        private long requestIdField;
        
        private int levelField;
        
        private System.DateTime timeStampField;
        
        private string messageIdField;
        
        private string messageField;
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public long RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public int Level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class ResponseHeader {
        
        private long requestIdField;
        
        private int statusField;
        
        private string orderNoField;
        
        private string statusMessageField;
        
        private string statusMessageIdField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private string reqUserField;
        
        private System.DateTime receivedDateField;
        
        private bool receivedDateFieldSpecified;
        
        private System.DateTime finishedDateField;
        
        private bool finishedDateFieldSpecified;
        
        /// <remarks/>
        public long RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public string StatusMessageId {
            get {
                return this.statusMessageIdField;
            }
            set {
                this.statusMessageIdField = value;
            }
        }
        
        /// <remarks/>
        public int Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ReqUser {
            get {
                return this.reqUserField;
            }
            set {
                this.reqUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedDate {
            get {
                return this.receivedDateField;
            }
            set {
                this.receivedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivedDateSpecified {
            get {
                return this.receivedDateFieldSpecified;
            }
            set {
                this.receivedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinishedDate {
            get {
                return this.finishedDateField;
            }
            set {
                this.finishedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FinishedDateSpecified {
            get {
                return this.finishedDateFieldSpecified;
            }
            set {
                this.finishedDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class Response {
        
        private ResponseHeader responseHeaderField;
        
        private Parameter[] responseParametersField;
        
        private Parameter[] requestParametersField;
        
        private Notification[] notificationsField;
        
        /// <remarks/>
        public ResponseHeader ResponseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Parameter[] ResponseParameters {
            get {
                return this.responseParametersField;
            }
            set {
                this.responseParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Parameter[] RequestParameters {
            get {
                return this.requestParametersField;
            }
            set {
                this.requestParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class Parameter {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class CreateRequest : InstantLinkRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class ModifyRequest : InstantLinkRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.comptel.com/2011/02/instantlink")]
    public partial class DisplayRequest : InstantLinkRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void modifyCompletedEventHandler(object sender, modifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void displayCompletedEventHandler(object sender, displayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class displayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal displayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getInstantLinkAvailabilityCompletedEventHandler(object sender, getInstantLinkAvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInstantLinkAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInstantLinkAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InstantLinkAvailabilityInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InstantLinkAvailabilityInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591