//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows", ConfigurationName="SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType")]
    public interface gestionServAdiDescuentoWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarDescHFC no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/registrarDescHFC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse1 registrarDescHFC(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarDescLTE no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/registrarDescLTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse1 registrarDescLTE(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types")]
    public partial class registrarDescHFCRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string codigoAplicacionField;
        
        private System.DateTime fechaProgramacionField;
        
        private string coIdField;
        
        private string codClienteField;
        
        private string desServicioPVUField;
        
        private string telefonoField;
        
        private string coSerField;
        
        private string emailUsuarioAppField;
        
        private string desCoSerField;
        
        private string nroCuentaField;
        
        private string cicloFacField;
        
        private string aplicaDescField;
        
        private string objIdField;
        
        private string siteObjIdField;
        
        private int idCampanaField;
        
        private double montoDescField;
        
        private int periodoDescField;
        
        private int flagDescField;
        
        private int snCodeField;
        
        private string notasField;
        
        private string destinatarioCorreoField;
        
        private string codigoEmpleadoField;
        
        private string codigoSistemaField;
        
        private string nroDocumentoField;
        
        private string planClienteField;
        
        private string nomClienteField;
        
        private string apeClienteField;
        
        private string descDACField;
        
        private string descTipoDocField;
        
        private string tipoClienteField;
        
        private string nomClienteCompletoField;
        
        private string nroClienteField;
        
        private string nomResponsableLegalField;
        
        private string costoServiciosinIGVField;
        
        private string costoServicioconIGVField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime fechaProgramacion {
            get {
                return this.fechaProgramacionField;
            }
            set {
                this.fechaProgramacionField = value;
                this.RaisePropertyChanged("fechaProgramacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
                this.RaisePropertyChanged("codCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DesServicioPVU {
            get {
                return this.desServicioPVUField;
            }
            set {
                this.desServicioPVUField = value;
                this.RaisePropertyChanged("DesServicioPVU");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string coSer {
            get {
                return this.coSerField;
            }
            set {
                this.coSerField = value;
                this.RaisePropertyChanged("coSer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string emailUsuarioApp {
            get {
                return this.emailUsuarioAppField;
            }
            set {
                this.emailUsuarioAppField = value;
                this.RaisePropertyChanged("emailUsuarioApp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string desCoSer {
            get {
                return this.desCoSerField;
            }
            set {
                this.desCoSerField = value;
                this.RaisePropertyChanged("desCoSer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string nroCuenta {
            get {
                return this.nroCuentaField;
            }
            set {
                this.nroCuentaField = value;
                this.RaisePropertyChanged("nroCuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cicloFac {
            get {
                return this.cicloFacField;
            }
            set {
                this.cicloFacField = value;
                this.RaisePropertyChanged("cicloFac");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string aplicaDesc {
            get {
                return this.aplicaDescField;
            }
            set {
                this.aplicaDescField = value;
                this.RaisePropertyChanged("aplicaDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string objId {
            get {
                return this.objIdField;
            }
            set {
                this.objIdField = value;
                this.RaisePropertyChanged("objId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string siteObjId {
            get {
                return this.siteObjIdField;
            }
            set {
                this.siteObjIdField = value;
                this.RaisePropertyChanged("siteObjId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int idCampana {
            get {
                return this.idCampanaField;
            }
            set {
                this.idCampanaField = value;
                this.RaisePropertyChanged("idCampana");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double MontoDesc {
            get {
                return this.montoDescField;
            }
            set {
                this.montoDescField = value;
                this.RaisePropertyChanged("MontoDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int PeriodoDesc {
            get {
                return this.periodoDescField;
            }
            set {
                this.periodoDescField = value;
                this.RaisePropertyChanged("PeriodoDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int FlagDesc {
            get {
                return this.flagDescField;
            }
            set {
                this.flagDescField = value;
                this.RaisePropertyChanged("FlagDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int SnCode {
            get {
                return this.snCodeField;
            }
            set {
                this.snCodeField = value;
                this.RaisePropertyChanged("SnCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("notas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string destinatarioCorreo {
            get {
                return this.destinatarioCorreoField;
            }
            set {
                this.destinatarioCorreoField = value;
                this.RaisePropertyChanged("destinatarioCorreo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string codigoEmpleado {
            get {
                return this.codigoEmpleadoField;
            }
            set {
                this.codigoEmpleadoField = value;
                this.RaisePropertyChanged("codigoEmpleado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PlanCliente {
            get {
                return this.planClienteField;
            }
            set {
                this.planClienteField = value;
                this.RaisePropertyChanged("PlanCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string NomCliente {
            get {
                return this.nomClienteField;
            }
            set {
                this.nomClienteField = value;
                this.RaisePropertyChanged("NomCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ApeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                this.apeClienteField = value;
                this.RaisePropertyChanged("ApeCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DescDAC {
            get {
                return this.descDACField;
            }
            set {
                this.descDACField = value;
                this.RaisePropertyChanged("DescDAC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DescTipoDoc {
            get {
                return this.descTipoDocField;
            }
            set {
                this.descTipoDocField = value;
                this.RaisePropertyChanged("DescTipoDoc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string TipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("TipoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string NomClienteCompleto {
            get {
                return this.nomClienteCompletoField;
            }
            set {
                this.nomClienteCompletoField = value;
                this.RaisePropertyChanged("NomClienteCompleto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string NroCliente {
            get {
                return this.nroClienteField;
            }
            set {
                this.nroClienteField = value;
                this.RaisePropertyChanged("NroCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string NomResponsableLegal {
            get {
                return this.nomResponsableLegalField;
            }
            set {
                this.nomResponsableLegalField = value;
                this.RaisePropertyChanged("NomResponsableLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string CostoServiciosinIGV {
            get {
                return this.costoServiciosinIGVField;
            }
            set {
                this.costoServiciosinIGVField = value;
                this.RaisePropertyChanged("CostoServiciosinIGV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string CostoServicioconIGV {
            get {
                return this.costoServicioconIGVField;
            }
            set {
                this.costoServicioconIGVField = value;
                this.RaisePropertyChanged("CostoServicioconIGV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class parametrosTypeObjetoOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types")]
    public partial class registrarDescHFCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDescHFCRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest registrarDescHFCRequest;
        
        public registrarDescHFCRequest1() {
        }
        
        public registrarDescHFCRequest1(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest registrarDescHFCRequest) {
            this.registrarDescHFCRequest = registrarDescHFCRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDescHFCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse registrarDescHFCResponse;
        
        public registrarDescHFCResponse1() {
        }
        
        public registrarDescHFCResponse1(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse registrarDescHFCResponse) {
            this.registrarDescHFCResponse = registrarDescHFCResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types")]
    public partial class registrarDescLTERequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private System.DateTime fechaProgramacionField;
        
        private string customerIdField;
        
        private string coIdField;
        
        private string msisdnField;
        
        private string coSerField;
        
        private string desCoSerField;
        
        private string nroCuentaField;
        
        private string cicloFacField;
        
        private string aplicaDescField;
        
        private string objIdField;
        
        private string siteObjIdField;
        
        private int idCampanaField;
        
        private double montoDescField;
        
        private int periodoDescField;
        
        private int flagDescField;
        
        private int snCodeField;
        
        private string notasField;
        
        private string destinatarioCorreoField;
        
        private string codigoEmpleadoField;
        
        private string codigoSistemaField;
        
        private string nroDocumentoField;
        
        private string planClienteField;
        
        private string nomClienteField;
        
        private string apeClienteField;
        
        private string descDACField;
        
        private string descTipoDocField;
        
        private string tipoClienteField;
        
        private string nomClienteCompletoField;
        
        private string nroClienteField;
        
        private string nomResponsableLegalField;
        
        private string costoServiciosinIGVField;
        
        private string costoServicioconIGVField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime fechaProgramacion {
            get {
                return this.fechaProgramacionField;
            }
            set {
                this.fechaProgramacionField = value;
                this.RaisePropertyChanged("fechaProgramacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string coSer {
            get {
                return this.coSerField;
            }
            set {
                this.coSerField = value;
                this.RaisePropertyChanged("coSer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string desCoSer {
            get {
                return this.desCoSerField;
            }
            set {
                this.desCoSerField = value;
                this.RaisePropertyChanged("desCoSer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string nroCuenta {
            get {
                return this.nroCuentaField;
            }
            set {
                this.nroCuentaField = value;
                this.RaisePropertyChanged("nroCuenta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string cicloFac {
            get {
                return this.cicloFacField;
            }
            set {
                this.cicloFacField = value;
                this.RaisePropertyChanged("cicloFac");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string aplicaDesc {
            get {
                return this.aplicaDescField;
            }
            set {
                this.aplicaDescField = value;
                this.RaisePropertyChanged("aplicaDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string objId {
            get {
                return this.objIdField;
            }
            set {
                this.objIdField = value;
                this.RaisePropertyChanged("objId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string siteObjId {
            get {
                return this.siteObjIdField;
            }
            set {
                this.siteObjIdField = value;
                this.RaisePropertyChanged("siteObjId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int idCampana {
            get {
                return this.idCampanaField;
            }
            set {
                this.idCampanaField = value;
                this.RaisePropertyChanged("idCampana");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double MontoDesc {
            get {
                return this.montoDescField;
            }
            set {
                this.montoDescField = value;
                this.RaisePropertyChanged("MontoDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int PeriodoDesc {
            get {
                return this.periodoDescField;
            }
            set {
                this.periodoDescField = value;
                this.RaisePropertyChanged("PeriodoDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int FlagDesc {
            get {
                return this.flagDescField;
            }
            set {
                this.flagDescField = value;
                this.RaisePropertyChanged("FlagDesc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int SnCode {
            get {
                return this.snCodeField;
            }
            set {
                this.snCodeField = value;
                this.RaisePropertyChanged("SnCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string notas {
            get {
                return this.notasField;
            }
            set {
                this.notasField = value;
                this.RaisePropertyChanged("notas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string destinatarioCorreo {
            get {
                return this.destinatarioCorreoField;
            }
            set {
                this.destinatarioCorreoField = value;
                this.RaisePropertyChanged("destinatarioCorreo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string codigoEmpleado {
            get {
                return this.codigoEmpleadoField;
            }
            set {
                this.codigoEmpleadoField = value;
                this.RaisePropertyChanged("codigoEmpleado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string codigoSistema {
            get {
                return this.codigoSistemaField;
            }
            set {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("codigoSistema");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string NroDocumento {
            get {
                return this.nroDocumentoField;
            }
            set {
                this.nroDocumentoField = value;
                this.RaisePropertyChanged("NroDocumento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PlanCliente {
            get {
                return this.planClienteField;
            }
            set {
                this.planClienteField = value;
                this.RaisePropertyChanged("PlanCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string NomCliente {
            get {
                return this.nomClienteField;
            }
            set {
                this.nomClienteField = value;
                this.RaisePropertyChanged("NomCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ApeCliente {
            get {
                return this.apeClienteField;
            }
            set {
                this.apeClienteField = value;
                this.RaisePropertyChanged("ApeCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string DescDAC {
            get {
                return this.descDACField;
            }
            set {
                this.descDACField = value;
                this.RaisePropertyChanged("DescDAC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DescTipoDoc {
            get {
                return this.descTipoDocField;
            }
            set {
                this.descTipoDocField = value;
                this.RaisePropertyChanged("DescTipoDoc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string TipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("TipoCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string NomClienteCompleto {
            get {
                return this.nomClienteCompletoField;
            }
            set {
                this.nomClienteCompletoField = value;
                this.RaisePropertyChanged("NomClienteCompleto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string NroCliente {
            get {
                return this.nroClienteField;
            }
            set {
                this.nroClienteField = value;
                this.RaisePropertyChanged("NroCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string NomResponsableLegal {
            get {
                return this.nomResponsableLegalField;
            }
            set {
                this.nomResponsableLegalField = value;
                this.RaisePropertyChanged("NomResponsableLegal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CostoServiciosinIGV {
            get {
                return this.costoServiciosinIGVField;
            }
            set {
                this.costoServiciosinIGVField = value;
                this.RaisePropertyChanged("CostoServiciosinIGV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string CostoServicioconIGV {
            get {
                return this.costoServicioconIGVField;
            }
            set {
                this.costoServicioconIGVField = value;
                this.RaisePropertyChanged("CostoServicioconIGV");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types")]
    public partial class registrarDescLTEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDescLTERequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest registrarDescLTERequest;
        
        public registrarDescLTERequest1() {
        }
        
        public registrarDescLTERequest1(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest registrarDescLTERequest) {
            this.registrarDescLTERequest = registrarDescLTERequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDescLTEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/gestionservadidescuentows/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse registrarDescLTEResponse;
        
        public registrarDescLTEResponse1() {
        }
        
        public registrarDescLTEResponse1(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse registrarDescLTEResponse) {
            this.registrarDescLTEResponse = registrarDescLTEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gestionServAdiDescuentoWSPortTypeChannel : Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gestionServAdiDescuentoWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType>, Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType {
        
        public gestionServAdiDescuentoWSPortTypeClient() {
        }
        
        public gestionServAdiDescuentoWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gestionServAdiDescuentoWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gestionServAdiDescuentoWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gestionServAdiDescuentoWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse1 Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType.registrarDescHFC(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest1 request) {
            return base.Channel.registrarDescHFC(request);
        }
        
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse registrarDescHFC(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest registrarDescHFCRequest) {
            Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest1 inValue = new Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCRequest1();
            inValue.registrarDescHFCRequest = registrarDescHFCRequest;
            Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescHFCResponse1 retVal = ((Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType)(this)).registrarDescHFC(inValue);
            return retVal.registrarDescHFCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse1 Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType.registrarDescLTE(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest1 request) {
            return base.Channel.registrarDescLTE(request);
        }
        
        public Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse registrarDescLTE(Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest registrarDescLTERequest) {
            Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest1 inValue = new Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTERequest1();
            inValue.registrarDescLTERequest = registrarDescLTERequest;
            Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.registrarDescLTEResponse1 retVal = ((Claro.SIACU.ProxyService.Transac.Service.SIAC.ServAdiDescuentoWS.gestionServAdiDescuentoWSPortType)(this)).registrarDescLTE(inValue);
            return retVal.registrarDescLTEResponse;
        }
    }
}
