//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultcodeField;
        
        private string faultstringField;
        
        private string faultactorField;
        
        private Detail detailField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
                this.RaisePropertyChanged("faultstring");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string faultactor {
            get {
                return this.faultactorField;
            }
            set {
                this.faultactorField = value;
                this.RaisePropertyChanged("faultactor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Detail detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public partial class Detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class ResponseOpcionalComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class PaginaOpcionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string opcicCodField;
        
        private string claveField;
        
        private string opcicDesField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string opcicCod {
            get {
                return this.opcicCodField;
            }
            set {
                this.opcicCodField = value;
                this.RaisePropertyChanged("opcicCod");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string opcicDes {
            get {
                return this.opcicDesField;
            }
            set {
                this.opcicDesField = value;
                this.RaisePropertyChanged("opcicDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class ListaPaginaOpcionesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PaginaOpcionType[] listaOpcionesField;
        
        private string codigoVendedorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaOpciones", IsNullable=true, Order=0)]
        public PaginaOpcionType[] listaOpciones {
            get {
                return this.listaOpcionesField;
            }
            set {
                this.listaOpcionesField = value;
                this.RaisePropertyChanged("listaOpciones");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoVendedor {
            get {
                return this.codigoVendedorField;
            }
            set {
                this.codigoVendedorField = value;
                this.RaisePropertyChanged("codigoVendedor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class AuditResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class RequestOpcionalComplexType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class PaginaOpcionesUsuarioRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int userField;
        
        private int aplicCodField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int aplicCod {
            get {
                return this.aplicCodField;
            }
            set {
                this.aplicCodField = value;
                this.RaisePropertyChanged("aplicCod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class AuditRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                this.usrAplicacionField = value;
                this.RaisePropertyChanged("usrAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws", ConfigurationName="SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType")]
    public interface ConsultaOpcionesAuditoriaPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación leerPaginaOpcionesPorUsuario no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws/leerPaginaO" +
            "pcionesPorUsuario", ReplyAction="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws/ConsultaOpc" +
            "ionesAuditoriaPortType/leerPaginaOpcionesPorUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.Fault), Action="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws/leerPaginaO" +
            "pcionesPorUsuario", Name="IntegrationError", Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse1 leerPaginaOpcionesPorUsuario(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string languageField;
        
        private string consumerField;
        
        private string systemField;
        
        private string moduloField;
        
        private string pidField;
        
        private string userIdField;
        
        private string dispositivoField;
        
        private string wsIpField;
        
        private string operationField;
        
        private System.DateTime timestampField;
        
        private string msgTypeField;
        
        private ArgType[] varArgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
                this.RaisePropertyChanged("modulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string wsIp {
            get {
                return this.wsIpField;
            }
            set {
                this.wsIpField = value;
                this.RaisePropertyChanged("wsIp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class ArgType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class leerPaginaOpcionesPorUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditRequest auditField;
        
        private PaginaOpcionesUsuarioRequest paginaOpcionesUsuarioRequestField;
        
        private RequestOpcionalComplexType[] listaOpcionalRequestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditRequest audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaginaOpcionesUsuarioRequest PaginaOpcionesUsuarioRequest {
            get {
                return this.paginaOpcionesUsuarioRequestField;
            }
            set {
                this.paginaOpcionesUsuarioRequestField = value;
                this.RaisePropertyChanged("PaginaOpcionesUsuarioRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RequestOpcional", IsNullable=false)]
        public RequestOpcionalComplexType[] listaOpcionalRequest {
            get {
                return this.listaOpcionalRequestField;
            }
            set {
                this.listaOpcionalRequestField = value;
                this.RaisePropertyChanged("listaOpcionalRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consumerField;
        
        private string pidField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private ArgType[] varArgField;
        
        private StatusType statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string codeField;
        
        private string messageField;
        
        private string msgidField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgid {
            get {
                return this.msgidField;
            }
            set {
                this.msgidField = value;
                this.RaisePropertyChanged("msgid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws")]
    public partial class leerPaginaOpcionesPorUsuarioResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditResponse auditField;
        
        private ListaPaginaOpcionesType paginaOpcionesUsuarioResponseField;
        
        private ResponseOpcionalComplexType[] listaOpcionalResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditResponse audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ListaPaginaOpcionesType PaginaOpcionesUsuarioResponse {
            get {
                return this.paginaOpcionesUsuarioResponseField;
            }
            set {
                this.paginaOpcionesUsuarioResponseField = value;
                this.RaisePropertyChanged("PaginaOpcionesUsuarioResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ResponseOpcional", IsNullable=false)]
        public ResponseOpcionalComplexType[] listaOpcionalResponse {
            get {
                return this.listaOpcionalResponseField;
            }
            set {
                this.listaOpcionalResponseField = value;
                this.RaisePropertyChanged("listaOpcionalResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class leerPaginaOpcionesPorUsuarioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderRequestType HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuario leerPaginaOpcionesPorUsuario;
        
        public leerPaginaOpcionesPorUsuarioRequest() {
        }
        
        public leerPaginaOpcionesPorUsuarioRequest(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuario leerPaginaOpcionesPorUsuario) {
            this.HeaderRequest = HeaderRequest;
            this.leerPaginaOpcionesPorUsuario = leerPaginaOpcionesPorUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class leerPaginaOpcionesPorUsuarioResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderResponseType HeaderResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.eai.auditoria.claro.com.pe/consultaopcionesauditoriaws", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse leerPaginaOpcionesPorUsuarioResponse;
        
        public leerPaginaOpcionesPorUsuarioResponse1() {
        }
        
        public leerPaginaOpcionesPorUsuarioResponse1(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderResponseType HeaderResponse, Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse leerPaginaOpcionesPorUsuarioResponse) {
            this.HeaderResponse = HeaderResponse;
            this.leerPaginaOpcionesPorUsuarioResponse = leerPaginaOpcionesPorUsuarioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaOpcionesAuditoriaPortTypeChannel : Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaOpcionesAuditoriaPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType>, Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType {
        
        public ConsultaOpcionesAuditoriaPortTypeClient() {
        }
        
        public ConsultaOpcionesAuditoriaPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaOpcionesAuditoriaPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaOpcionesAuditoriaPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaOpcionesAuditoriaPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse1 Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType.leerPaginaOpcionesPorUsuario(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioRequest request) {
            return base.Channel.leerPaginaOpcionesPorUsuario(request);
        }
        
        public Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderResponseType leerPaginaOpcionesPorUsuario(Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuario leerPaginaOpcionesPorUsuario1, out Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse leerPaginaOpcionesPorUsuarioResponse) {
            Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioRequest inValue = new Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.leerPaginaOpcionesPorUsuario = leerPaginaOpcionesPorUsuario1;
            Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.leerPaginaOpcionesPorUsuarioResponse1 retVal = ((Claro.SIACU.ProxyService.Transac.Service.SIACSecurity.Permissions.LPOPU.ConsultaOpcionesAuditoriaPortType)(this)).leerPaginaOpcionesPorUsuario(inValue);
            leerPaginaOpcionesPorUsuarioResponse = retVal.leerPaginaOpcionesPorUsuarioResponse;
            return retVal.HeaderResponse;
        }
    }
}
