//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws", ConfigurationName="SIACU.WSRegisterTraceability.registrarTrazabilidadPortType")]
    public interface registrarTrazabilidadPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarTrazabilidad no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse registrarTrazabilidad(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse> registrarTrazabilidadAsync(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class registrarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private parametrosAuditRequest auditRequestField;
        
        private parametrosBiometria biometriaField;
        
        private ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionalesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public parametrosAuditRequest auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public parametrosBiometria biometria {
            get {
                return this.biometriaField;
            }
            set {
                this.biometriaField = value;
                this.RaisePropertyChanged("biometria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("campoAdicional", IsNullable=false)]
        public ListaCamposAdicionalesTypeCampoAdicional[] listaCamposAdicionales {
            get {
                return this.listaCamposAdicionalesField;
            }
            set {
                this.listaCamposAdicionalesField = value;
                this.RaisePropertyChanged("listaCamposAdicionales");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class parametrosAuditRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class parametrosAuditResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string codRespuestaField;
        
        private string msjRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codRespuesta {
            get {
                return this.codRespuestaField;
            }
            set {
                this.codRespuestaField = value;
                this.RaisePropertyChanged("codRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string msjRespuesta {
            get {
                return this.msjRespuestaField;
            }
            set {
                this.msjRespuestaField = value;
                this.RaisePropertyChanged("msjRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class parametrosBiometria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPadreField;
        
        private string codOperacionField;
        
        private string sistemaField;
        
        private string codCanalField;
        
        private string codPdvField;
        
        private string codModalVentaField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string lineasField;
        
        private string veprnIdField;
        
        private string dniAutorizadoField;
        
        private string usuarioCtaRedField;
        
        private string idHijoField;
        
        private string padreAntField;
        
        private string dniConsultadoField;
        
        private string wsOrigenField;
        
        private string tipoValidacionField;
        
        private string origenTipoField;
        
        private string codigoErrorField;
        
        private string mensajeProcesoField;
        
        private string estadoField;
        
        private string flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idPadre {
            get {
                return this.idPadreField;
            }
            set {
                this.idPadreField = value;
                this.RaisePropertyChanged("idPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codOperacion {
            get {
                return this.codOperacionField;
            }
            set {
                this.codOperacionField = value;
                this.RaisePropertyChanged("codOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
                this.RaisePropertyChanged("sistema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string codCanal {
            get {
                return this.codCanalField;
            }
            set {
                this.codCanalField = value;
                this.RaisePropertyChanged("codCanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codPdv {
            get {
                return this.codPdvField;
            }
            set {
                this.codPdvField = value;
                this.RaisePropertyChanged("codPdv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string codModalVenta {
            get {
                return this.codModalVentaField;
            }
            set {
                this.codModalVentaField = value;
                this.RaisePropertyChanged("codModalVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string lineas {
            get {
                return this.lineasField;
            }
            set {
                this.lineasField = value;
                this.RaisePropertyChanged("lineas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string veprnId {
            get {
                return this.veprnIdField;
            }
            set {
                this.veprnIdField = value;
                this.RaisePropertyChanged("veprnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string dniAutorizado {
            get {
                return this.dniAutorizadoField;
            }
            set {
                this.dniAutorizadoField = value;
                this.RaisePropertyChanged("dniAutorizado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string usuarioCtaRed {
            get {
                return this.usuarioCtaRedField;
            }
            set {
                this.usuarioCtaRedField = value;
                this.RaisePropertyChanged("usuarioCtaRed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string idHijo {
            get {
                return this.idHijoField;
            }
            set {
                this.idHijoField = value;
                this.RaisePropertyChanged("idHijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string padreAnt {
            get {
                return this.padreAntField;
            }
            set {
                this.padreAntField = value;
                this.RaisePropertyChanged("padreAnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string dniConsultado {
            get {
                return this.dniConsultadoField;
            }
            set {
                this.dniConsultadoField = value;
                this.RaisePropertyChanged("dniConsultado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string wsOrigen {
            get {
                return this.wsOrigenField;
            }
            set {
                this.wsOrigenField = value;
                this.RaisePropertyChanged("wsOrigen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string tipoValidacion {
            get {
                return this.tipoValidacionField;
            }
            set {
                this.tipoValidacionField = value;
                this.RaisePropertyChanged("tipoValidacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string origenTipo {
            get {
                return this.origenTipoField;
            }
            set {
                this.origenTipoField = value;
                this.RaisePropertyChanged("origenTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string mensajeProceso {
            get {
                return this.mensajeProcesoField;
            }
            set {
                this.mensajeProcesoField = value;
                this.RaisePropertyChanged("mensajeProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class ListaCamposAdicionalesTypeCampoAdicional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreCampoField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreCampo {
            get {
                return this.nombreCampoField;
            }
            set {
                this.nombreCampoField = value;
                this.RaisePropertyChanged("nombreCampo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types")]
    public partial class registrarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private parametrosAuditResponse auditResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public parametrosAuditResponse auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarTrazabilidadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarRequest registrarRequest;
        
        public registrarTrazabilidadRequest() {
        }
        
        public registrarTrazabilidadRequest(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarRequest registrarRequest) {
            this.registrarRequest = registrarRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarTrazabilidadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/RegistrarTrazabilidad/ws/types", Order=0)]
        public Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarResponse registrarResponse;
        
        public registrarTrazabilidadResponse() {
        }
        
        public registrarTrazabilidadResponse(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarResponse registrarResponse) {
            this.registrarResponse = registrarResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface registrarTrazabilidadPortTypeChannel : Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class registrarTrazabilidadPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType>, Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType {
        
        public registrarTrazabilidadPortTypeClient() {
        }
        
        public registrarTrazabilidadPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public registrarTrazabilidadPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public registrarTrazabilidadPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public registrarTrazabilidadPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType.registrarTrazabilidad(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest request) {
            return base.Channel.registrarTrazabilidad(request);
        }
        
        public Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarResponse registrarTrazabilidad(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarRequest registrarRequest) {
            Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest inValue = new Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest();
            inValue.registrarRequest = registrarRequest;
            Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse retVal = ((Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType)(this)).registrarTrazabilidad(inValue);
            return retVal.registrarResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse> Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType.registrarTrazabilidadAsync(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest request) {
            return base.Channel.registrarTrazabilidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadResponse> registrarTrazabilidadAsync(Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarRequest registrarRequest) {
            Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest inValue = new Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadRequest();
            inValue.registrarRequest = registrarRequest;
            return ((Claro.SIACU.ProxyService.Transac.Service.SIACU.WSRegisterTraceability.registrarTrazabilidadPortType)(this)).registrarTrazabilidadAsync(inValue);
        }
    }
}
